Add RancherOS section to README
grisu48/pasta pull request #20
Opened 2020-12-31 21:46 UTC by pdostal

As we now have [pasta.sh.cvut.cz](https://pasta.sh.cvut.cz/) I'm sharing the steps describing the deployment on [RancherOS](https://rancher.com/docs/os/v1.x/en/).

2021-01-01 02:00 UTC, tuxjz requested changes

2021-01-01 02:00 UTC, tuxjz commented on README.md
> +$ # mktable - gpt - mkpart - 0% - 100%
missing partition number after mkpart command

2021-01-01 02:00 UTC, tuxjz commented on cloud-init.yaml.example
> +          - 172.16.0.2/24
``` suggestion
          - 192.0.2.2/24
```

2021-01-01 02:00 UTC, tuxjz commented on cloud-init.yaml.example
> +        gateway: 172.16.0.1
``` suggestion
        gateway: 192.0.2.1
```

2021-01-01 02:00 UTC, tuxjz commented on cloud-init.yaml.example
> +          - 2001:123:456::2/64
``` suggestion
          - 2001:db8::2/64
```

2021-01-01 02:00 UTC, tuxjz commented on cloud-init.yaml.example
> +        gateway_ipv6: 2001:123:456::1
``` suggestion
        gateway_ipv6: 2001:db8::1
```

2021-01-01 02:18 UTC, tuxjz approved these changes
Good job 🙃 🥂

2021-01-03 17:14 UTC, grisu48 commented
LGTM :rocket: Thanks for the PR! :slightly_smiling_face:

2021-01-03 17:14 UTC, merged